### Function missingDataHeatmap ###
#' Function missingDataHeatmap
#'
#' Takes a dataframe as input and highlights where data is missing with a heatmap.  No clustering
#' is performed by default.
#'
#' @author John Thompson, \email{john.thompson@@bms.com}
#' @keywords missing data heatmap
#'
#' @param data A dataframe with rownames to examine
#' @param filename Optionally provide a filename to save the graphic to a file instead of
#'   sending to the console
#' @param title Optional text title for the plot
#' @param fontsize base fontsize for the plot (Default = 10)
#' @param Rowv clustering specification for rows (Default = NA) See ?NMF::heatmap for clustering options
#' @param Colv clustering specification for columns (Default = NA) See ?NMF::heatmap for clustering options
#' @param color Color map for the heatmap (Default = c("firebrick2", "white", "dodgerblue3")) See ?NMF:aheatmap for color options.
#' @param ...  Other arguments to pass to NMF::aheatmap
#'
#' @return A heatmap generated by aheatmap
#'
#' @examples
#'
#'    #make up some data with one row of NAs
#'    df <- data.frame(Doubles=c(1:10, NA, 12:20),
#'                     Characters=c(rep("A",10), NA, rep("B",9)),
#'                     stringsAsFactors=FALSE)
#'    rownames(df) <- paste("A", rownames(df), sep="")
#'
#'    #Draw a heatmap of missing data
#'    missingDataHeatmap (df)
#'
#'    #Save the heatmap to a file
#'    missingDataHeatmap (df, filename="./output/MyHeatmap.png")
#'
#'    #apply some extra aheatmap options
#'    missingDataHeatmap(df, title="Test Title", legend=FALSE, sub="Red indicates missing data")
#'
#' @import magrittr
#' @importFrom NMF aheatmap
#' @importFrom assertthat assert_that
#'
#' @export
missingDataHeatmap <- function(data, filename, title="", fontsize=10, Rowv=NA, Colv=NA,
                               color=c("firebrick2", "white","dodgerblue3"), ...) {

  assertthat::assert_that("data.frame" %in% class(data))

  #create a matrix of 1's the same shape as data
  bindata <- matrix(1, nrow=nrow(data), ncol=ncol(data),
                      dimnames=dimnames(data))

  #Convert missing data cells in data to zeros in the matrix
  bindata[is.na(data)] <- 0

  if (missing(filename)){
    NMF::aheatmap(bindata, Rowv = NA, Colv = NA,
                  border_color = "grey70",
                  main=title,
                  fontsize=fontsize,
                  color=color,
                  ...)
  } else {
    NMF::aheatmap(bindata, Rowv = NA, Colv = NA,
                  border_color = "grey70",
                  main=title,
                  fontsize=fontsize,
                  color=color,
                  filename=filename,
                  ...)
  }
}
